/**
 * 菜单图标注册表。
 *
 * 菜单的 icon 字段存的是「语义 slug」（如 models / agents），不是 lucide 组件名。
 * 侧边栏（AppLayout）与「菜单管理」的图标选择器共用这张表，保证选择器里能选到的图标，
 * 侧边栏一定渲染得出来；未注册的 slug 侧边栏会回退到 DEFAULT_MENU_ICON。
 *
 * 图标全部取自项目当前使用的图标库 lucide-vue-next。新增图标前请确认
 * node_modules/lucide-vue-next/dist/esm/icons/<kebab-name>.js 存在（升级图标库会改名/删除）。
 * 既有 slug 不可重命名：数据库存量菜单行按 slug 解析图标。
 */
import type { Component } from 'vue'
import {
  Activity,
  Archive,
  Bell,
  Book,
  BookOpen,
  Bookmark,
  Bot,
  Boxes,
  Briefcase,
  Bug,
  Building2,
  Cable,
  CalendarDays,
  ChartColumn,
  ChartLine,
  ChartPie,
  ClipboardList,
  Clock,
  Cloud,
  Code,
  Cpu,
  CreditCard,
  Database,
  Download,
  Eye,
  FileCode,
  FileText,
  Files,
  Fingerprint,
  Flag,
  FlaskConical,
  Folder,
  FolderOpen,
  Gauge,
  GitBranch,
  Globe,
  GraduationCap,
  HardDrive,
  Heart,
  History,
  Image,
  Inbox,
  Info,
  Kanban,
  KeyRound,
  Layers,
  LayoutDashboard,
  Link,
  ListTree,
  Lock,
  Mail,
  MapPin,
  Megaphone,
  MessageSquare,
  Network,
  Package,
  Palette,
  Play,
  Plug,
  Puzzle,
  Receipt,
  RefreshCw,
  Rocket,
  ScanFace,
  ScrollText,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Star,
  Table,
  Tag,
  Tags,
  Terminal,
  Timer,
  Trash2,
  TrendingUp,
  Upload,
  User,
  UserCog,
  Users,
  Wallet,
  Workflow,
  Wrench,
  Zap
} from 'lucide-vue-next'

/** slug → lucide 图标组件。 */
export const MENU_ICON_MAP: Record<string, Component> = {
  // ---- 既有 slug：数据库种子与存量菜单行在用，勿改名 ----
  dashboard: LayoutDashboard,
  resource: Layers,
  system: Settings,
  ops: Gauge,
  models: Boxes,
  agents: Bot,
  'knowledge-bases': Database,
  'store-instances': Server,
  files: Files,
  'mcp-servers': Cable,
  skills: Sparkles,
  workflows: Workflow,
  users: Users,
  roles: ShieldCheck,
  menus: ListTree,
  clients: KeyRound,
  'api-keys': KeyRound,
  logs: ScrollText,
  observability: Activity,
  chat: MessageSquare,
  settings: Info,
  // ---- 通用图标：供菜单管理里按需挑选 ----
  analytics: ChartLine,
  chart: ChartColumn,
  report: ChartPie,
  trend: TrendingUp,
  calendar: CalendarDays,
  clock: Clock,
  history: History,
  timer: Timer,
  bell: Bell,
  mail: Mail,
  send: Send,
  inbox: Inbox,
  megaphone: Megaphone,
  cloud: Cloud,
  globe: Globe,
  network: Network,
  'map-pin': MapPin,
  terminal: Terminal,
  code: Code,
  'git-branch': GitBranch,
  bug: Bug,
  cpu: Cpu,
  'hard-drive': HardDrive,
  package: Package,
  archive: Archive,
  folder: Folder,
  'folder-open': FolderOpen,
  'file-text': FileText,
  'file-code': FileCode,
  book: Book,
  'book-open': BookOpen,
  'graduation-cap': GraduationCap,
  'clipboard-list': ClipboardList,
  table: Table,
  kanban: Kanban,
  bookmark: Bookmark,
  tag: Tag,
  tags: Tags,
  star: Star,
  heart: Heart,
  flag: Flag,
  image: Image,
  receipt: Receipt,
  'credit-card': CreditCard,
  wallet: Wallet,
  'shopping-cart': ShoppingCart,
  briefcase: Briefcase,
  building: Building2,
  user: User,
  'user-cog': UserCog,
  shield: Shield,
  fingerprint: Fingerprint,
  'scan-face': ScanFace,
  lock: Lock,
  search: Search,
  eye: Eye,
  upload: Upload,
  download: Download,
  link: Link,
  rocket: Rocket,
  zap: Zap,
  puzzle: Puzzle,
  plug: Plug,
  palette: Palette,
  play: Play,
  refresh: RefreshCw,
  trash: Trash2,
  wrench: Wrench,
  flask: FlaskConical
}

/** slug 为空或未注册时的兜底图标。 */
export const DEFAULT_MENU_ICON: Component = LayoutDashboard

/** 按 slug 解析菜单图标组件。 */
export function resolveMenuIcon(slug?: string | null): Component {
  return (slug ? MENU_ICON_MAP[slug] : undefined) ?? DEFAULT_MENU_ICON
}

/** 图标选择器选项（按 slug 升序，图标由使用方渲染）。 */
export const MENU_ICON_OPTIONS: { label: string; value: string }[] = Object.keys(MENU_ICON_MAP)
  .sort()
  .map((slug) => ({ label: slug, value: slug }))
