<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>xin.v5ai.nb</groupId>
        <artifactId>v5ai-common</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>v5ai-common-translation</artifactId>

    <description>
        v5ai-common-translation 通用翻译功能
    </description>

    <dependencies>

        <!-- 序列化模块 -->
        <dependency>
            <groupId>xin.v5ai.nb</groupId>
            <artifactId>v5ai-common-json</artifactId>
        </dependency>
        <!-- api模块 -->
        <dependency>
            <groupId>xin.v5ai.nb</groupId>
            <artifactId>v5ai-api</artifactId>
        </dependency>
    </dependencies>
</project>