<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>xin.v5ai.nb</groupId>
        <artifactId>v5ai-common</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>v5ai-common-milvus</artifactId>

    <description>
        v5ai-common-milvus Milvus客户端
    </description>

    <dependencies>
        <dependency>
            <groupId>xin.v5ai.nb</groupId>
            <artifactId>v5ai-common-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.milvus</groupId>
            <artifactId>milvus-sdk-java</artifactId>
        </dependency>
    </dependencies>

</project>