<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>xin.v5ai.nb</groupId>
    <artifactId>v5ai-common-bom</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <description>
        v5ai-common-bom common依赖项
    </description>

    <properties>
        <revision>0.1.0-SNAPSHOT</revision>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>xin.v5ai.nb</groupId>
                <artifactId>v5ai-common-core</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>xin.v5ai.nb</groupId>
                <artifactId>v5ai-common-json</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>xin.v5ai.nb</groupId>
                <artifactId>v5ai-common-agentscope</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>xin.v5ai.nb</groupId>
                <artifactId>v5ai-common-mybatis</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>xin.v5ai.nb</groupId>
                <artifactId>v5ai-common-log</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>xin.v5ai.nb</groupId>
                <artifactId>v5ai-common-encrypt</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>xin.v5ai.nb</groupId>
                <artifactId>v5ai-common-redis</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>xin.v5ai.nb</groupId>
                <artifactId>v5ai-common-satoken</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>xin.v5ai.nb</groupId>
                <artifactId>v5ai-common-security</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>xin.v5ai.nb</groupId>
                <artifactId>v5ai-common-storage</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>xin.v5ai.nb</groupId>
                <artifactId>v5ai-common-sensitive</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>xin.v5ai.nb</groupId>
                <artifactId>v5ai-common-translation</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>xin.v5ai.nb</groupId>
                <artifactId>v5ai-common-web</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>xin.v5ai.nb</groupId>
                <artifactId>v5ai-common-elasticsearch</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>xin.v5ai.nb</groupId>
                <artifactId>v5ai-common-milvus</artifactId>
                <version>${revision}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>