package xin.v5ai.nb.agent.core;

import io.agentscope.core.message.Msg;
import io.agentscope.core.message.MsgRole;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import tools.jackson.core.JacksonException;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;
import xin.v5ai.nb.common.agentscope.core.ModelChatClient;
import xin.v5ai.nb.common.agentscope.core.exception.ModelChatException;

import java.time.Duration;
import java.util.ArrayList;
import java.util.List;

/**
 * 基于 AgentScope 模型的 AgentDTO 配置生成器：
 * 根据用户描述，要求模型输出严格 JSON（name/description/greeting/presetQuestions/systemPrompt），
 * 解析后回填「新建智能体」向导。模型对话经 {@link ModelChatClient} 发起。
 */
@Slf4j
@Component
public class AgentScopeAgentConfigGenerator implements AgentConfigGenerator {

    private static final int MAX_RESPONSE_CHARS = 20000;
    private final ObjectMapper objectMapper = new ObjectMapper();

    private final ModelChatClient modelChatClient;
    private final Duration timeout;

    public AgentScopeAgentConfigGenerator(
            ModelChatClient modelChatClient,
            @Value("${v5ai.model.connection.test.timeout.ms:90000}") long timeoutMillis
    ) {
        this.modelChatClient = modelChatClient;
        this.timeout = Duration.ofMillis(timeoutMillis);
    }

    @Override
    public GeneratedAgentConfig generate(Long modelId, String description) {
        if (modelId == null) {
            throw new IllegalArgumentException("model is required");
        }
        if (description == null || description.isBlank()) {
            throw new IllegalArgumentException("description is required");
        }
        var messages = List.of(
                Msg.builder().role(MsgRole.SYSTEM)
                        .textContent("""
                                You are a professional AI application designer. Based on the user's description, \
                                design an AI agent and return ONLY a JSON object (no markdown code fences, no extra text) with exactly these fields:
                                - "name": short agent name, no more than 20 characters
                                - "description": one or two sentences describing what the agent does
                                - "greeting": a friendly welcome message shown when a conversation starts
                                - "presetQuestions": an array of 3 to 5 typical questions users might ask
                                - "systemPrompt": a complete system prompt that defines the agent's role, tone and behaviour
                                """)
                        .build(),
                Msg.builder().role(MsgRole.USER).textContent(description).build());

        String raw;
        long started = System.currentTimeMillis();
        try {
            raw = modelChatClient.chatText(modelId, messages, timeout);
        } catch (ModelChatException exception) {
            log.warn("agent config generation failed for model {}: {}", modelId, exception.getMessage());
            throw new IllegalArgumentException("模型生成失败: " + friendlyMessage(exception), exception);
        }
        long elapsed = System.currentTimeMillis() - started;
        log.info("agent config generated by model {} in {}ms", modelId, elapsed);
        return parse(raw);
    }

    private GeneratedAgentConfig parse(String raw) {
        var json = stripCodeFence(raw);
        try {
            JsonNode node = objectMapper.readTree(json);
            if (node == null || !node.isObject()) {
                throw new IllegalArgumentException("模型输出不是 JSON 对象");
            }
            var name = text(node, "name");
            var description = text(node, "description");
            var greeting = text(node, "greeting");
            var systemPrompt = text(node, "systemPrompt");
            var presetQuestions = new ArrayList<String>();
            var array = node.path("presetQuestions");
            if (array.isArray()) {
                array.forEach(item -> {
                    var question = item.asText("").trim();
                    if (!question.isEmpty()) {
                        presetQuestions.add(question);
                    }
                });
            }
            if (name.isEmpty()) {
                throw new IllegalArgumentException("模型未返回 agent 名称（name）");
            }
            return new GeneratedAgentConfig(name, description, greeting, presetQuestions, systemPrompt);
        } catch (JacksonException exception) {
            throw new IllegalArgumentException("模型输出无法解析为 JSON: " + truncate(raw));
        }
    }

    private static String text(JsonNode node, String field) {
        return node.path(field).asText("").trim();
    }

    /** 剥离模型常见的 ```json ... ``` 代码围栏。 */
    private static String stripCodeFence(String raw) {
        var s = raw == null ? "" : raw.trim();
        if (s.startsWith("```")) {
            int firstNewline = s.indexOf('\n');
            int lastFence = s.lastIndexOf("```");
            if (firstNewline > 0 && lastFence > firstNewline) {
                s = s.substring(firstNewline + 1, lastFence).trim();
            }
        }
        return s;
    }

    private static String friendlyMessage(Exception exception) {
        var detail = exception.getMessage();
        if (detail != null && detail.contains("timed out")) {
            return "模型响应超时，请检查模型连通性";
        }
        return detail == null || detail.isBlank() ? exception.getClass().getSimpleName() : detail;
    }

    private static String truncate(String value) {
        if (value == null) {
            return "";
        }
        return value.length() <= MAX_RESPONSE_CHARS ? value : value.substring(0, MAX_RESPONSE_CHARS) + "...";
    }
}
